name: login_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+4
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  firebase_auth: ^1.1.4
  google_sign_in: ^5.0.3
  font_awesome_flutter: ^9.0.0
  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.2
  magnifier: ^0.0.5
  table_calendar: ^2.2.1
  auto_size_text: ^2.1.0
  easy_localization: ^3.0.0
  path_provider: ^1.1.0
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.10
  cron: ^0.3.2
  flutter_tts: ^3.1.0
  path:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true