Map<int, Map<dynamic, dynamic>> Sehirler = {
  0 : {
    "isim" : "İstanbul",
    "tür" : "Büyük Şehir",
    "tarih" : "Türkiye'de Marmara Bölgesi'nde yer alan şehir ve Türkiye Cumhuriyeti Devletinin 81 ilinden biridir. Ülkenin nüfus bakımından en çok göç alan ve en kalabalık ilidir. Ekonomik, tarihî ve sosyo-kültürel açıdan önde gelen şehirlerden biridir.[6][7][8] Şehir, iktisadi büyüklük açısından dünyada 34. sırada yer alır. Nüfuslarına göre şehirler listesinde belediye sınırları göz önüne alınarak yapılan sıralamaya göre Avrupa'da birinci, dünyada ise altıncı sırada yer almaktadır.[9][10]İstanbul Türkiye'nin kuzeybatısında, Marmara kıyısı ve Boğaziçi boyunca, Haliç'i de çevreleyecek şekilde kurulmuştur. İstanbul kıtalararası bir şehir olup, Avrupa'daki bölümüne Avrupa Yakası veya Rumeli Yakası, Asya'daki bölümüne ise Anadolu Yakası veya Asya Yakası denir. Tarihte ilk olarak üç tarafı Marmara Denizi, Boğaziçi ve Haliç'in sardığı bir yarımada üzerinde kurulan İstanbul'un batıdaki sınırını İstanbul Surları oluşturmaktaydı. Gelişme ve büyüme sürecinde surların her seferinde daha batıya ilerletilerek inşa edilmesiyle 4 defa genişletilen şehrin[11] 39 ilçesi vardır. Sınırları içerisinde ise büyükşehir belediyesi ile birlikte toplam 40 belediye bulunmaktadır.",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],
    "puan" : 4,
    "ziyaret" : 123484,
    "kalp" : 21524,
    "resim" : "lib/Server/istanbul.jpg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ],
    "mekanlar" : ["Ayasofya", "Kız Kulesi"],
    "benzerler" : ["Kahramanmaraş", "İzmir"],
  },
  1 : {
    "isim" : "İzmir",
    "tür" : "Büyük Şehir",
    "tarih" : "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan önde gelen şehirlerden biridir. Nüfusu 2020 itibarıyla 4.394.694 kişidir. Yüzölçümü olarak ülkenin yirmi üçüncü büyük ilidir.[6][7] Etrafı Aydın, Balıkesir, Manisa illeri ve Ege Denizi ve Ege Adaları ile çevrilidir.Antik Çağ'ın ünlü kentleri arasında yer alan Smyrna, İyon kültürünün zenginliklerini bünyesinde barındıran bir şehir olarak adını duyuruyordu. Bu maksatla da bu şehre (İyonya'nın İncisi) deniyordu. İzmir Körfezi çevresinde bulunan şehir, her yıl İzmir Enternasyonal Fuarı'nı düzenleyen önemli bir fuar merkezi ve liman kentidir. İzmir'in batısında denizi, plajları ve termal merkezleriyle Urla Yarımadası uzanır. İzmir, yatlar ve gemilerle çevrilmiş uzun ve dar bir körfezin başında yer almaktadır. Sahil boyunca palmiye, hurma ağaçları ve geniş caddeler bulunmaktadır. İzmir Limanı, Türkiye'nin en büyük yedinci limanıdır.",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],    "puan" : 3,
    "ziyaret" : 123456,
    "kalp" : 53524,
    "resim" : "lib/Server/izmir.jpg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ],
    "mekanlar" : ["İzmir Saat Kulesi"],
    "benzerler" : ["Kahramanmaraş", "İstanbul"],
  },
  2 : {
    "isim" : "Kahramanmaraş",
    "tür" : "Şehir",
    "tarih" : "Kahramanmaraş, eski ve halk arasındaki adıyla Maraş, Türkiye'nin Akdeniz Bölgesinde bulunan bir ili ve en kalabalık on sekizinci kentidir. Kurtuluş Savaşı'nda işgale direnişi nedeniyle TBMM tarafından 5 Nisan 1925'te şehre İstiklal Madalyası verilmiştir. Maraş olan adı, 7 Şubat 1973'te Kahramanmaraş olarak değiştirilmiştir.Geç Hitit şehri olan Gurgum’un bulunduğu yerde kurulmuştur. Sistematik bir kazı yapılmamış olmasına rağmen birçok Hitit anıtı bulunmuştur.[2]Osmanlı seyyahı Evliya Çelebi, seyahatnamesinde Maraş halkı için, kelimatları lisan-ı Türkidir ve ekseriya halkı Türkmendir der.[3] Maraş ve çevresi başta Oğuzların Avşar, Bayat ve Beğdili boyları çoğunlukta olmakla birlikte hemen hemen 24 Oğuz boyunun tamamı mevcuttur.2012'de çıkarılan 6360 sayılı kanun ile büyükşehir olmuştur. Aynı zamanda il sınırları içerisinde bulunan Afşin - Elbistan A, B, C termik santralleri sayesinde Kahramanmaraş, Türkiye'nin elektrik ihtiyacının %14'ünü karşılamaktadır.[4]Dövme dondurması, tarhanası ve biberi şehrin önemli tescilli gıdalarıdır. 2021 itibarıyla %1,22 artarak 1.168.163 nüfusa ulaşmıştır.[5]",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],    "puan" : 4,
    "ziyaret" : 12984,
    "kalp" : 12884,
    "resim" : "lib/Server/kahramanmaraş.jpg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ],
    "mekanlar" : ["Ayasofya", "Kız Kulesi", "İzmir Saat Kulesi"],
    "benzerler" : ["İstanbul"],
  },
};

Map<int, Map<String, dynamic>> Binalar = {
  0 : {
    "isim" : "Ayasofya",
    "mekan" : "İbadetHane",
    "tarih" : "Ayasofya veya resmî ismiyle Ayasofya-i Kebîr Câmi-i Şerîfi, eski ismiyle Ayasofya Kilisesi, İstanbul'da yer alan bir cami, eski bazilika, katedral ve müze. Bizans İmparatoru I. Justinianus tarafından, 532-537 yılları arasında İstanbul'un tarihî yarımadasındaki eski şehir merkezine inşa ettirilmiş bazilika planlı bir patrik katedrali olup 1453 yılında İstanbul'un Osmanlılar tarafından fethedilmesinden sonra Fatih Sultan Mehmed tarafından camiye dönüştürülmüştür. 1934 yılında yayımlanan Bakanlar Kurulu Kararnamesi ile müzeye dönüştürülmüş, kazı ve tadilat çalışmaları başlatılmış ve 1935-2020 yılları arasında müze olarak hizmet vermiştir. 2020 yılında ise müze statüsünün iptal edilmesiyle tekrar cami statüsü kazanmıştır.Ayasofya, mimari bakımdan merkezî planı birleştiren kubbeli bazilika tipinde bir yapı olup kubbe geçişi ve taşıyıcı sistem özellikleriyle mimarlık tarihinde önemli bir dönüm noktası olarak ele alınır.Ayasofya adındaki sözcüğü anlamına gelir. sözcüğü ise Eski Yunancada anlamındaki sophos sözcüğünden gelir.[4] Dolayısıyla 'aya sofya [5] Miletli İsidoros ve Trallesli AnthemiusAyas Justinianu'un bu iş için büyük bir servet harcadığı belirtilir.[10] Bu çok eski binanın bir özelliği, yapımında kullanılan bazı sütun, kapı ve taşların binadan daha eski yapı ve tapınaklardan getirilmiş olmasıdır.",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],    "puan" : 4,
    "ziyaret" : 128484,
    "kalp" : 21524,
    "resim" : "lib/Server/ayasofya.jpg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ]
  },
  1 : {
    "isim" : "Kız Kulesi",
    "mekan" : "Rstoran",
    "tarih" : "Kız Kulesi, hakkında çeşitli rivayetler anlatılan, efsanelere konu olan, İstanbul Boğazı'nın Marmara Denizi'ne yakın kısmında, Salacak açıklarında yer alan küçük adacık üzerinde inşa edilmiş yapıdır. Üsküdar'ın sembolü haline gelen kule, Üsküdar’da Bizans devrinden kalan tek eserdir. MÖ 24 yıllarına kadar uzanan tarihi bir geçmişe sahip olan kule, Karadeniz’in Marmara ile birleştiği yerde küçük bir ada üzerinde kurulmuştur. Bazı Avrupalı tarihçiler buraya Leander Kulesi derler. Kule hakkında pek çok rivayetler bulunmaktadır. Evliya Çelebi kuleyi şöyle tarif eder:“	Deniz içinde karadan bir ok atımı uzak, dört köşe, sanatkarane yapılmış bir yüksek kuledir. Yüksekliği tam 80 (seksen) arşındır. Sathı mesehası iki yüz adımdır. İki taraftan kapısı vardır.	„Bugün görülen kulenin temelleri ve alt katın önemli kısımları II. Mehmed devri yapısıdır. Kulenin etrafındaki sahanlık geniş kaplanmıştır. Üstündeki madalyon halindeki bir mermer levhada, kuleye şimdiki şeklini veren Sultan II. Mahmud'un, Hattat Rasim’in kaleminden çıkmış 1832 tarihli bir tuğrası vardır. Kulenin Eminönü tarafı daha genişçe olup burada bir de sarnıç vardır.",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],    "puan" : 3,
    "ziyaret" : 123456,
    "kalp" : 53524,
    "resim" : "lib/Server/kızkulesi.jpg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ]
  },
  2 : {
    "isim" : "İzmir Saat Kulesi",
    "mekan" : "Anıt",
    "tarih" : "İzmir Saat Kulesi, İzmir'de Osmanlı padişahı II. Abdülhamid'in tahta çıkışının 25. yıldönümünü kutlamak için 1901'de inşa edilmiş tarihî saat kulesidir. Konak Meydanı'ndaki İzmir Hükûmet Konağı, Kemeraltı Çarşısı girişi, Konak Yalı Camii ve İzmir Büyükşehir Belediyesi binası arasındaki alanda yer alır. 25 metre yüksekliğinde ve dört katlı olan kule, Sultan II. Abdülhamid'in iradesi gereği Osmanlı vilayetlerinde aynı dönemde meydana getirilmiş birçok saat kulesinden birisidir. Ancak özgün mimarisi ve yapımında izlenen yöntem nedeniyle diğer saat kuleleri arasında özel bir yer edinmiştir.[1] Osmanlı saat kuleleri içinde en estetik görünüşlü ve en zarifi olarak kabul edilir.[2]Fransız mimar Raymond Charles Péré tarafından tasarlanan kulenin saatinin Alman İmparatoru II. Wilhelm tarafından hediye edildiğine dair kayıtlar vardır.[1]",
    "hava" : [["PRT", 25.5, "bulutlu",],["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",], ["PRT", 25.5, "bulutlu",]],    "puan" : 3,
    "ziyaret" : 123456,
    "kalp" : 53524,
    "resim" : "lib/Server/izmirsaatkulesi.jpeg",
    "mesajlar" : [
      ['Kullanıcı1', 3.2, DateTime(2021, 6, 5), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı2', 5.0, DateTime(2021, 9, 4), 'Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'],
      ['Kullanıcı3', 5.0, DateTime(2021, 8, 5), "İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan"],
      ['Kullanıcı4', 4.1, DateTime(2021, 11, 7), 'Mesaj4'],
      ['Kullanıcı5', 2.9, DateTime(2021, 9, 12), 'Mesaj5'],
    ]
  },
};

List<String> TrendSehir = ["İstanbul", "Kahramanmaraş",];

List<String> StarSehirler = ["İstanbul", "İzmir",];

Map<int, Map<dynamic, dynamic>> Planlar = {
  0 : {
    "isim" : "Plan 1",
    "baslangic" : "5 Şubat 2021",
    "bitis" : "27 şubat 2021",
    "plan" : [[DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "başlangıç", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 1", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 2", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 3", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 4", 1],
      [DateTime(2021, 2, 9, 13, 30), DateTime(2021, 2, 9, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 5", 1],
      [DateTime(2021, 2, 10, 13, 30), DateTime(2021, 2, 10, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 6", 1],
      [DateTime(2021, 2, 11, 13, 30), DateTime(2021, 2, 11, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 7", 1],
      [DateTime(2021, 2, 12, 13, 30), DateTime(2021, 2, 12, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "son", 1],],
  },
  1 : {
    "isim" : "Plan 2",
    "baslangic" : "5 Şubat 2021",
    "bitis" : "27 şubat 2021",
    "plan" : [[DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "başlangıç", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 1", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 2", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 3", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 4", 1],
      [DateTime(2021, 2, 9, 13, 30), DateTime(2021, 2, 9, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 5", 1],
      [DateTime(2021, 2, 10, 13, 30), DateTime(2021, 2, 10, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 6", 1],
      [DateTime(2021, 2, 11, 13, 30), DateTime(2021, 2, 11, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 7", 1],
      [DateTime(2021, 2, 12, 13, 30), DateTime(2021, 2, 12, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "son", 1],],
  },
  2 : {
    "isim" : "Plan 3",
    "baslangic" : "5 Şubat 2021",
    "bitis" : "27 şubat 2021",
    "plan" : [[DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "başlangıç", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 1", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 2", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 3", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 4", 1],
      [DateTime(2021, 2, 9, 13, 30), DateTime(2021, 2, 9, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 5", 1],
      [DateTime(2021, 2, 10, 13, 30), DateTime(2021, 2, 10, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 6", 1],
      [DateTime(2021, 2, 11, 13, 30), DateTime(2021, 2, 11, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 7", 1],
      [DateTime(2021, 2, 12, 13, 30), DateTime(2021, 2, 12, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "son", 1],],
  },
  3 : {
    "isim" : "Plan 4",
    "baslangic" : "5 Şubat 2021",
    "bitis" : "27 şubat 2021",
    "plan" : [[DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "başlangıç", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 1", 1],
      [DateTime(2021, 2, 7, 13, 30), DateTime(2021, 2, 7, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 2", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 3", 1],
      [DateTime(2021, 2, 8, 13, 30), DateTime(2021, 2, 8, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 4", 1],
      [DateTime(2021, 2, 9, 13, 30), DateTime(2021, 2, 9, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 5", 1],
      [DateTime(2021, 2, 10, 13, 30), DateTime(2021, 2, 10, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 6", 1],
      [DateTime(2021, 2, 11, 13, 30), DateTime(2021, 2, 11, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "ayasofya ziyareti 7", 1],
      [DateTime(2021, 2, 12, 13, 30), DateTime(2021, 2, 12, 17, 30), "ibadethane", "lib/Server/ayasofya.jpg", "son", 1],],
  },
};